# Linear regression from scratch

In [101]:
class Linearregression:

    def _init_(self):
        self.m = m
        self.b = b

    def fit(self,x_train,y_train):

        
        num = 0
        den = 0
        
        for i in range(x_train.shape[0]):
            
            num = num + ((x_train[i] - x_train.mean())*(y_train[i] - y_train.mean()))
            den = den + ((x_train[i] - x_train.mean())*(x_train[i] - x_train.mean()))
        
        self.m = num/den
        self.b = y_train.mean() - (self.m * x_train.mean())
        print(self.m)
        print(self.b)  

    def predict(self,x_test):

        print(x_test)

        

        return self.m * x_test + self.b

In [8]:
import pandas as pd
import seaborn as sns
import numpy as np

In [11]:
h = pd.read_csv("Housing (1).csv")
h.head(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished

In [12]:
h = h.drop(columns=[ 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus','bedrooms'])

In [13]:
h.sample(3)

       price  area
437  3290000  5880
435  3290000  4040
498  2660000  2000

In [15]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split



sv = linear_model.LinearRegression()

In [96]:
sv.fit(h[['price']],h.area)

LinearRegression()

In [97]:
sv.predict([[3920000]])

C:\Users\Prabhath\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([4623.97691965])

In [21]:
sv.intercept_

np.float64(2387308.4823964303)

In [20]:
sv.coef_

array([461.97489427])

In [22]:
o = 461.9*8580+2387308.4
print(o)

6350410.4

In [46]:
X = h['price'].values
y = h['area'].values

In [54]:
X

array([13300000, 12250000, 12250000, 12215000, 11410000, 10850000,
       10150000, 10150000,  9870000,  9800000,  9800000,  9681000,
        9310000,  9240000,  9240000,  9100000,  9100000,  8960000,
        8890000,  8855000,  8750000,  8680000,  8645000,  8645000,
        8575000,  8540000,  8463000,  8400000,  8400000,  8400000,
        8400000,  8400000,  8295000,  8190000,  8120000,  8080940,
        8043000,  7980000,  7962500,  7910000,  7875000,  7840000,
        7700000,  7700000,  7560000,  7560000,  7525000,  7490000,
        7455000,  7420000,  7420000,  7420000,  7350000,  7350000,
        7350000,  7350000,  7343000,  7245000,  7210000,  7210000,
        7140000,  7070000,  7070000,  7035000,  7000000,  6930000,
        6930000,  6895000,  6860000,  6790000,  6790000,  6755000,
        6720000,  6685000,  6650000,  6650000,  6650000,  6650000,
        6650000,  6650000,  6629000,  6615000,  6615000,  6580000,
        6510000,  6510000,  6510000,  6475000,  6475000,  6440000,
        6440000,  6419000,  6405000,  6300000,  6300000,  6300000,
        6300000,  6300000,  6293000,  6265000,  6230000,  6230000,
        6195000,  6195000,  6195000,  6160000,  6160000,  6125000,
        6107500,  6090000,  6090000,  6090000,  6083000,  6083000,
        6020000,  6020000,  6020000,  5950000,  5950000,  5950000,
        5950000,  5950000,  5950000,  5950000,  5950000,  5943000,
        5880000,  5880000,  5873000,  5873000,  5866000,  5810000,
        5810000,  5810000,  5803000,  5775000,  5740000,  5740000,
        5740000,  5740000,  5740000,  5652500,  5600000,  5600000,
        5600000,  5600000,  5600000,  5600000,  5600000,  5600000,
        5600000,  5565000,  5565000,  5530000,  5530000,  5530000,
        5523000,  5495000,  5495000,  5460000,  5460000,  5460000,
        5460000,  5425000,  5390000,  5383000,  5320000,  5285000,
        5250000,  5250000,  5250000,  5250000,  5250000,  5250000,
        5250000,  5250000,  5250000,  5243000,  5229000,  5215000,
        5215000,  5215000,  5145000,  5145000,  5110000,  5110000,
        5110000,  5110000,  5075000,  5040000,  5040000,  5040000,
        5040000,  5033000,  5005000,  4970000,  4970000,  4956000,
        4935000,  4907000,  4900000,  4900000,  4900000,  4900000,
        4900000,  4900000,  4900000,  4900000,  4900000,  4900000,
        4900000,  4900000,  4893000,  4893000,  4865000,  4830000,
        4830000,  4830000,  4830000,  4795000,  4795000,  4767000,
        4760000,  4760000,  4760000,  4753000,  4690000,  4690000,
        4690000,  4690000,  4690000,  4690000,  4655000,  4620000,
        4620000,  4620000,  4620000,  4620000,  4613000,  4585000,
        4585000,  4550000,  4550000,  4550000,  4550000,  4550000,
        4550000,  4550000,  4543000,  4543000,  4515000,  4515000,
        4515000,  4515000,  4480000,  4480000,  4480000,  4480000,
        4480000,  4473000,  4473000,  4473000,  4445000,  4410000,
        4410000,  4403000,  4403000,  4403000,  4382000,  4375000,
        4340000,  4340000,  4340000,  4340000,  4340000,  4319000,
        4305000,  4305000,  4277000,  4270000,  4270000,  4270000,
        4270000,  4270000,  4270000,  4235000,  4235000,  4200000,
        4200000,  4200000,  4200000,  4200000,  4200000,  4200000,
        4200000,  4200000,  4200000,  4200000,  4200000,  4200000,
        4200000,  4200000,  4200000,  4200000,  4193000,  4193000,
        4165000,  4165000,  4165000,  4130000,  4130000,  4123000,
        4098500,  4095000,  4095000,  4095000,  4060000,  4060000,
        4060000,  4060000,  4060000,  4025000,  4025000,  4025000,
        4007500,  4007500,  3990000,  3990000,  3990000,  3990000,
        3990000,  3920000,  3920000,  3920000,  3920000,  3920000,
        3920000,  3920000,  3885000,  3885000,  3850000,  3850000,
        3850000,  3850000,  3850000,  3850000,  3850000,  3836000,
        3815000,  3780000,  3780000,  3780000,  3780000,  3780000,
        3780000,  3773000,  3773000,  3773000,  3745000,  3710000,
        3710000,  3710000,  3710000,  3710000,  3703000,  3703000,
        3675000,  3675000,  3675000,  3675000,  3640000,  3640000,
        3640000,  3640000,  3640000,  3640000,  3640000,  3640000,
        3640000,  3633000,  3605000,  3605000,  3570000,  3570000,
        3570000,  3570000,  3535000,  3500000,  3500000,  3500000,
        3500000,  3500000,  3500000,  3500000,  3500000,  3500000,
        3500000,  3500000,  3500000,  3500000,  3500000,  3500000,
        3500000,  3500000,  3493000,  3465000,  3465000,  3465000,
        3430000,  3430000,  3430000,  3430000,  3430000,  3430000,
        3423000,  3395000,  3395000,  3395000,  3360000,  3360000,
        3360000,  3360000,  3360000,  3360000,  3360000,  3360000,
        3353000,  3332000,  3325000,  3325000,  3290000,  3290000,
        3290000,  3290000,  3290000,  3290000,  3290000,  3290000,
        3255000,  3255000,  3234000,  3220000,  3220000,  3220000,
        3220000,  3150000,  3150000,  3150000,  3150000,  3150000,
        3150000,  3150000,  3150000,  3150000,  3143000,  3129000,
        3118850,  3115000,  3115000,  3115000,  3087000,  3080000,
        3080000,  3080000,  3080000,  3045000,  3010000,  3010000,
        3010000,  3010000,  3010000,  3010000,  3010000,  3003000,
        2975000,  2961000,  2940000,  2940000,  2940000,  2940000,
        2940000,  2940000,  2940000,  2940000,  2870000,  2870000,
        2870000,  2870000,  2852500,  2835000,  2835000,  2835000,
        2800000,  2800000,  2730000,  2730000,  2695000,  2660000,
        2660000,  2660000,  2660000,  2660000,  2660000,  2660000,
        2653000,  2653000,  2604000,  2590000,  2590000,  2590000,
        2520000,  2520000,  2520000,  2485000,  2485000,  2450000,
        2450000,  2450000,  2450000,  2450000,  2450000,  2408000,
        2380000,  2380000,  2380000,  2345000,  2310000,  2275000,
        2275000,  2275000,  2240000,  2233000,  2135000,  2100000,
        2100000,  2100000,  1960000,  1890000,  1890000,  1855000,
        1820000,  1767150,  1750000,  1750000,  1750000])

In [55]:
y

array([ 7420,  8960,  9960,  7500,  7420,  7500,  8580, 16200,  8100,
        5750, 13200,  6000,  6550,  3500,  7800,  6000,  6600,  8500,
        4600,  6420,  4320,  7155,  8050,  4560,  8800,  6540,  6000,
        8875,  7950,  5500,  7475,  7000,  4880,  5960,  6840,  7000,
        7482,  9000,  6000,  6000,  6550,  6360,  6480,  6000,  6000,
        6000,  6000,  6600,  4300,  7440,  7440,  6325,  6000,  5150,
        6000,  6000, 11440,  9000,  7680,  6000,  6000,  8880,  6240,
        6360, 11175,  8880, 13200,  7700,  6000, 12090,  4000,  6000,
        5020,  6600,  4040,  4260,  6420,  6500,  5700,  6000,  6000,
        4000, 10500,  6000,  3760,  8250,  6670,  3960,  7410,  8580,
        5000,  6750,  4800,  7200,  6000,  4100,  9000,  6400,  6600,
        6000,  6600,  5500,  5500,  6350,  5500,  4500,  5450,  6420,
        3240,  6615,  6600,  8372,  4300,  9620,  6800,  8000,  6900,
        3700,  6420,  7020,  6540,  7231,  6254,  7320,  6525, 15600,
        7160,  6500,  5500, 11460,  4800,  5828,  5200,  4800,  7000,
        6000,  5400,  4640,  5000,  6360,  5800,  6660, 10500,  4800,
        4700,  5000, 10500,  5500,  6360,  6600,  5136,  4400,  5400,
        3300,  3650,  6100,  6900,  2817,  7980,  3150,  6210,  6100,
        6600,  6825,  6710,  6450,  7800,  4600,  4260,  6540,  5500,
       10269,  8400,  5300,  3800,  9800,  8520,  6050,  7085,  3180,
        4500,  7200,  3410,  7980,  3000,  3000, 11410,  6100,  5720,
        3540,  7600, 10700,  6600,  4800,  8150,  4410,  7686,  2800,
        5948,  4200,  4520,  4095,  4120,  5400,  4770,  6300,  5800,
        3000,  2970,  6720,  4646, 12900,  3420,  4995,  4350,  4160,
        6040,  6862,  4815,  7000,  8100,  3420,  9166,  6321, 10240,
        6440,  5170,  6000,  3630,  9667,  5400,  4320,  3745,  4160,
        3880,  5680,  2870,  5010,  4510,  4000,  3840,  3760,  3640,
        2550,  5320,  5360,  3520,  8400,  4100,  4990,  3510,  3450,
        9860,  3520,  4510,  5885,  4000,  8250,  4040,  6360,  3162,
        3510,  3750,  3968,  4900,  2880,  4880,  4920,  4950,  3900,
        4500,  1905,  4075,  3500,  6450,  4032,  4400, 10360,  3400,
        6360,  6360,  4500,  2175,  4360,  7770,  6650,  2787,  5500,
        5040,  5850,  2610,  2953,  2747,  4410,  4000,  2325,  4600,
        3640,  5800,  7000,  4079,  3520,  2145,  4500,  8250,  3450,
        4840,  4080,  4046,  4632,  5985,  6060,  3600,  3680,  4040,
        5600,  5900,  4992,  4340,  3000,  4320,  3630,  3460,  5400,
        4500,  3460,  4100,  6480,  4500,  3960,  4050,  7260,  5500,
        3000,  3290,  3816,  8080,  2145,  3780,  3180,  5300,  3180,
        7152,  4080,  3850,  2015,  2176,  3350,  3150,  4820,  3420,
        3600,  5830,  2856,  8400,  8250,  2520,  6930,  3480,  3600,
        4040,  6020,  4050,  3584,  3120,  5450,  3630,  3630,  5640,
        3600,  4280,  3570,  3180,  3000,  3520,  5960,  4130,  2850,
        2275,  3520,  4500,  4000,  3150,  4500,  4500,  3640,  3850,
        4240,  3650,  4600,  2135,  3036,  3990,  7424,  3480,  3600,
        3640,  5900,  3120,  7350,  3512,  9500,  5880, 12944,  4900,
        3060,  5320,  2145,  4000,  3185,  3850,  2145,  2610,  1950,
        4040,  4785,  3450,  3640,  3500,  4960,  4120,  4750,  3720,
        3750,  3100,  3185,  2700,  2145,  4040,  4775,  2500,  3180,
        6060,  3480,  3792,  4040,  2145,  5880,  4500,  3930,  3640,
        4370,  2684,  4320,  3120,  3450,  3986,  3500,  4095,  1650,
        3450,  6750,  9000,  3069,  4500,  5495,  2398,  3000,  3850,
        3500,  8100,  4960,  2160,  3090,  4500,  3800,  3090,  3240,
        2835,  4600,  5076,  3750,  3630,  8050,  4352,  3000,  5850,
        4960,  3600,  3660,  3480,  2700,  3150,  6615,  3040,  3630,
        6000,  5400,  5200,  3300,  4350,  2640,  2650,  3960,  6800,
        4000,  4000,  3934,  2000,  3630,  2800,  2430,  3480,  4000,
        3185,  4000,  2910,  3600,  4400,  3600,  2880,  3180,  3000,
        4400,  3000,  3210,  3240,  3000,  3500,  4840,  7700,  3635,
        2475,  2787,  3264,  3640,  3180,  1836,  3970,  3970,  1950,
        5300,  3000,  2400,  3000,  3360,  3420,  1700,  3649,  2990,
        3000,  2400,  3620,  2910,  3850])

In [61]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=2)

In [62]:
x_train.shape

(381,)

In [63]:
x_test.shape

(164,)

In [102]:
lr = Linearregression()

In [103]:
lr.fit(x_train,y_train)

0.0006152613871950286
2183.67855119164

In [104]:
x_train.shape[0]

381

In [105]:
x_train[0]

np.int64(5320000)

In [106]:
x_train.mean()

np.float64(4742177.007874016)

In [107]:
print(lr.predict(x_test[0]))

3920000
4595.503188996152

In [108]:
##y = mx * c

In [109]:
df = pd.read_csv('placement.csv')